--changeset luke:ddl:createTable:customers
CREATE TABLE "customers" (
                             "customer_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             "persona_id" varchar(250) NOT NULL UNIQUE
);
--rollback DROP TABLE "customers";

--changeset luke:ddl:createTable:orders
CREATE TABLE "orders" (
                          "order_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "customer_id" INT NOT NULL,
                          "quantity" INT NOT NULL,
                          "status_id" INT NOT NULL DEFAULT 1,
                          "total_cost" int NOT NULL
);
--rollback DROP TABLE "orders";

--changeset luke:ddl:createTable:status
CREATE TABLE "status" (
                          "status_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "status_name" varchar(30)
);
--rollback DROP TABLE "status";

--changeset luke:ddl:createTable:products
CREATE TABLE "products" (
                            "product_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "price" INT NOT NULL,
                            "VAT" INT NOT NULL
);
--rollback DROP TABLE "products";

--changeset luke:dml:insert:status
ALTER TABLE "orders" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("customer_id");
--rollback ALTER TABLE "orders" DROP CONSTRAINT "orders_customer_id_fkey";

--changeset luke:dml:insert:status
ALTER TABLE "orders" ADD FOREIGN KEY ("status_id") REFERENCES "status" ("status_id");
--rollback ALTER TABLE "orders" DROP CONSTRAINT "orders_status_id_fkey";

--changeset luke:dml:insert:status
INSERT INTO "status" ("status_name") VALUES
                                         ('placed'),
                                         ('pending'),
                                         ('approved'),
                                         ('denied'),
                                         ('cancelled'),
                                         ('collected');
--rollback DELETE FROM "status" WHERE "status_name" IN ('placed', 'pending', 'approved', 'denied', 'cancelled', 'collected');

--changeset luke:dml:insert:products
INSERT INTO "products" ("price", "VAT") VALUES
                                         (100, 15);
--rollback DELETE FROM "products" WHERE "price" = 100 AND "VAT" = 15;

--changeset luke:dml:insert:customers
INSERT INTO "customers" ("persona_id") VALUES
                                                        ('124332'),
                                                        ('213213'),
                                                        ('21321');
--rollback DELETE FROM "customers" WHERE "persona_id" IN ('124332', '213213', '21321');